# Generated by Django 5.1.2 on 2024-10-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
